# Demonstration of pandas for data science!

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

## 1. Creating pandas dataframes
1. Import from csv
2. Create from numpy array
3. Create from dictionary

In [4]:
# from csv
df_csv = pd.read_csv('./train.csv')
df_csv.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
# from numpy array
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df_array = pd.DataFrame(array,columns=['A','B','C'])
df_array.sample()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


A  B  C
1  4  5  6

In [26]:
# from dictionary
names = ['Boon Seng', 'Ali', 'Sharon', 'Jessie', 'Faizal', 'Wei Ming', 'Siti']
gender = ['M', 'M', 'F', 'F', 'M', 'M', 'F']
id_number = [2, 1, 3, 4, 5, 6, 7]
score = [74, 76, 77, 81, 72, 71, 91]
df_dict = pd.DataFrame({'names':names, 'gender':gender, 'id_number':id_number, 'score':score}).set_index('id_number')
df_dict


names gender  score
id_number                         
2          Boon Seng      M     74
1                Ali      M     76
3             Sharon      F     77
4             Jessie      F     81
5             Faizal      M     72
6           Wei Ming      M     71
7               Siti      F     91

## 2. Assessing pandas values
1. Get column names
2. Get index values
3. Get pandas as array
4. Get data slice by index
5. Get data slice by value

In [116]:
print(df_csv.columns)
print('\n')
print(df_dict.index)
print('\n')
print(df_array.values)
print('\n')
print(df_array.iloc[:2,:2])
print('\n')
print(df_array.loc[1:2,'A'])

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


Int64Index([2, 1, 3, 4, 5, 6, 7], dtype='int64', name='id_number')


[[1 2 3]
 [4 5 6]
 [7 8 9]]


   A  B
0  1  2
1  4  5


1    4
2    7
Name: A, dtype: int32


## 3. Useful pandas functions
1. df.info()
2. df.describe()
3. df.nunique()
4. df.value_counts()
5. df.astype('category').cat.codes

In [106]:
print(df_csv.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB
None


In [107]:
display(df_csv.describe())


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [108]:
print(df_csv.nunique())


PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64


In [111]:
print(df_csv['Embarked'].value_counts())

S    644
C    168
Q     77
Name: Embarked, dtype: int64


In [110]:
print(df_csv['Sex'].head(5))
print(df_csv['Sex'].astype('category').cat.codes.head(5))

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object
0    1
1    0
2    0
3    0
4    1
dtype: int8


## 4. Merging and joining
Multiple ways to achieve the same result. Merge, Join, Concat.  
Everything can be done between merge and concat.

In [32]:
# concaternating along different axes
display(pd.concat([df_dict,df_dict],axis=1))
display(pd.concat([df_dict,df_dict],axis=0))

names gender  score      names gender  score
id_number                                                  
2          Boon Seng      M     74  Boon Seng      M     74
1                Ali      M     76        Ali      M     76
3             Sharon      F     77     Sharon      F     77
4             Jessie      F     81     Jessie      F     81
5             Faizal      M     72     Faizal      M     72
6           Wei Ming      M     71   Wei Ming      M     71
7               Siti      F     91       Siti      F     91

names gender  score
id_number                         
2          Boon Seng      M     74
1                Ali      M     76
3             Sharon      F     77
4             Jessie      F     81
5             Faizal      M     72
6           Wei Ming      M     71
7               Siti      F     91
2          Boon Seng      M     74
1                Ali      M     76
3             Sharon      F     77
4             Jessie      F     81
5             Faizal      M     72
6           Wei Ming      M     71
7               Siti      F     91

In [40]:
# Merging 2 datasets
df_gender = pd.DataFrame({'gender_short':['M','F'],'gender_full':['male','female']}).set_index('gender_short')
display(df_gender)
df_merged = pd.merge(df_dict,df_gender,how='inner',left_on='gender',right_on='gender_short')
df_merged

gender_full
gender_short            
M                   male
F                 female

names gender  score gender_full
0  Boon Seng      M     74        male
1        Ali      M     76        male
2     Faizal      M     72        male
3   Wei Ming      M     71        male
4     Sharon      F     77      female
5     Jessie      F     81      female
6       Siti      F     91      female

## 5. Groupbys, crosstabs
for a list of aggregation functions, see:
http://pandas.pydata.org/pandas-docs/stable/groupby.html#aggregation

In [45]:
# groupby
display( df_dict.groupby(gender).count() )
display( df_dict.groupby(gender).mean() )

names  gender  score
F      3       3      3
M      4       4      4

score
F  83.00
M  73.25

In [46]:
# crosstab
df_dict['favourite drink'] = ['orange juice', 'soda', 'milk', 'tea', 'soda', 'orange juice', 'coffee']
df_dict['favourite food'] = ['hamburgers', 'satay', 'salad', 'sushi', 'satay', 'hamburgers', 'salad']
display(pd.crosstab(df_dict['favourite drink'],df_dict['favourite food']))

favourite food   hamburgers  salad  satay  sushi
favourite drink                                 
coffee                    0      1      0      0
milk                      0      1      0      0
orange juice              2      0      0      0
soda                      0      0      2      0
tea                       0      0      0      1

## 6. Iterating through the dataframe
1. Do not use iterrows!
2. use .apply() and lambda functions
3. itertuples can be even faster but less flexible

In [86]:
%%time
# using iterrows
df_random  = pd.DataFrame({'s1':np.random.randn(2000), 's2':np.random.randn(2000)})
for index, row in df_random.iterrows():
    row['s3'] = row['s1']+row['s2']

Wall time: 2.1 s


In [87]:
%%time
# using apply
df_random  = pd.DataFrame({'s1':np.random.randn(2000), 's2':np.random.randn(2000)})
def func(row):
    return row['s1']+row['s2']
df_random['s3'] = df_random.apply(lambda x: func(x),axis=1)

Wall time: 152 ms


In [90]:
%%time
# using itertuples
df_random  = pd.DataFrame({'s1':np.random.randn(2000), 's2':np.random.randn(2000)})
df_random['s3'] = df_random['s2']
for row in df_random.itertuples():
    df_random['s3'].iloc[row[0]] = row[1]+row[2]

Wall time: 488 ms


## These functions will get you through 90% of data cleaning and preperation. For more advanced processes, Stack Overflow is your best friend!